# Created using wingetcreate

PackageIdentifier: Microsoft.PowerToys
PackageVersion: 0.41.4
MinimumOSVersion: 10.0.17134.0
InstallerType: exe
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.41.4/PowerToysSetup-0.41.4-x64.exe
  InstallerSha256: 15BC88A752F1D32AAD1242897663BBB5C502203E44545A84625FED2C75FC55C4
  ProductCode: '{4A3949D5-8C9F-46D1-BBA6-921B56A90A23}'
ManifestType: installer
ManifestVersion: 1.0.0
